### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by JonathanChiang** [JonathanChiang/habits#3]
**Leave of Absence Forms:** 
- [x] Dates in Hospital
- [x] Coordinate Forms

**Comment by JonathanChiang** [comment]
**Startup Stuff** 

- [x] Setup Meeting with Dr. Schulman
- [ ] Setup Meeting with Curt Langlotz 
- [x] Follow up with Bank of America 
- [x] Sell Etrades Stock (Intel) 
- [x] Logo Design 
- [ ] [Contact NAMI](https://www.nami.org/Local-NAMI?state=CA)

**Comment by JonathanChiang** [comment]
**Applications:**

- [ ] NSF
- [ ] [Stanford BMI](https://biosciences.stanford.edu/prospective-students/how-to-apply/) 
- [ ] Knight Hennessy 
- [ ] Take GRE 
- [ ] Personal Statement 
- [ ] Resume

**Comment by JonathanChiang** [comment]
**Jon Chen's Coding:** 
- [ ] First Ten Users Debug 
- [ ] Code Sharing with Conor

**Comment by JonathanChiang** [comment]
**MGH Coding:**
[Slack Channel](https://app.slack.com/client/T0T5BEA1E/C6ZHAEPF1)
- [ ] Close Issues on Github 
- [ ] Documentation Push Github 
- [ ] Coordinate with Jayashree and Ken Chang 
- [ ] Pair Programming with Mose: 
- [ ] [Cases for Jon](https://www.dropbox.com/s/sqdsx0z3ty95wrz/CasesForJon.zip?dl=0&file_subpath=%2FCasesForJon%2FW2%2FFLAIR)

**Comment by JonathanChiang** [comment]
**Daniel Rubin's Coding:** 

- [ ] Niranjan Monday (3:30 Monday) 
- [ ] Follow Up with Dr. Rubin

**Comment by JonathanChiang** [comment]
https://www.dropbox.com/s/sqdsx0z3ty95wrz/CasesForJon.zip?dl=0&file_subpath=%2FCasesForJon%2FW2%2FFLAIR
